# Site settings
title: Jörg Hokamp
email: info@joerghokamp.de
description: > # this means to ignore newlines until "baseurl:"
  Hi! I'm Joerg Hokamp - Linux enthusiast, open-source fan,
  embedded developer and it-consultant.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jhokamp.github.io" # the base hostname & protocol for your site
twitter_username: hamburgkind
github_username:  jhokamp
css: "cyan"

# Build settings
markdown: kramdown
highlighter: null #pygments
lsi: false
safe: false
